import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Card from "@/components/card";
import { DUMMY_PRODUCTS } from "@/dummy-products";
import Image from "next/image";
import logo from "../../public/logo.png";
import ShoppingCard from "@/components/shoppingCard";
import CardModal from "@/components/cardModal";
import { useState } from "react";
import { log } from "console";

export default function Home() {
  const [isDialog, setIsDialog] = useState(false);
  const [shoppingCardItems, setShoppingCartItems] = useState<any>({
    items: [],
  });
  function handleOpenDialogClick() {
    setIsDialog(true);
  }
  function handleCloseDialogClick() {
    setIsDialog(false);
  }
  function addItemToCart(id: any) {
    setShoppingCartItems((prev: any) => {
      const updatedItems = [...prev.items];
      const existingCarItemIndex = updatedItems.findIndex(
        (cartItem) => cartItem.id === id
      );
      const existingCartItem = updatedItems[existingCarItemIndex];
      if (existingCartItem) {
        const updatedItem = {
          ...existingCartItem,
          quantity: existingCartItem.quantity + 1,
        };
        updatedItems[existingCarItemIndex] = updatedItem;
      } else {
        const product = DUMMY_PRODUCTS.find((product) => product.id === id);
        updatedItems.push({
          id: id,
          name: product!.title,
          price: product!.price,
          quantity: 1,
        });
      }
      return {
        items: updatedItems,
      };
    });
  }

  const totalQuantity = shoppingCardItems.items
    .map((element: any) => element.quantity)
    .reduce((a: any, b: any) => a + b, 0);

  return (
    <>
      <Head>
        <title>use context</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.mainContainer}>
        <nav className={styles.nav}>
          <div className={styles.logoContainer}>
            <Image
              src={logo}
              width={200}
              height={200}
              alt="logo"
              className={styles.img}
            />
          </div>
          <h1>ELEGANT CONTEXT</h1>
          <div className={styles.shoppingCard}>
            <ShoppingCard
              quantity={totalQuantity}
              onClick={handleOpenDialogClick}
            />
          </div>
        </nav>

        <div className={styles.sectionContainer}>
          <h3>ELEGANT CLOTHING FOR EVERYONE</h3>
          {isDialog && (
            <div className={styles.modal}>
              <CardModal onClick={handleCloseDialogClick} />
            </div>
          )}
          <ul className={styles.ulContainer}>
            {DUMMY_PRODUCTS.map((element) => {
              return (
                <li key={element.id}>
                  <Card
                    onClick={() => addItemToCart(element.id)}
                    title={element.title}
                    description={element.description}
                    price={element.price}
                    img={element.image}
                  />
                </li>
              );
            })}
          </ul>
        </div>
      </main>
    </>
  );
}
