import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Card from "@/components/card";
import { DUMMY_PRODUCTS } from "@/dummy-products";
import Image from "next/image";
import logo from "../../public/logo.png";
import ShoppingCard from "@/components/shoppingCard";
import CardModal from "@/components/cardModal";
import { useState } from "react";

export default function Home() {
  const [isDialog, setIsDialog] = useState(false);

  function handleOpenDialogClick() {
    setIsDialog(true);
  }
  function handleCloseDialogClick() {
    setIsDialog(false);
  }

  return (
    <>
      <Head>
        <title>use context</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.mainContainer}>
        <nav className={styles.nav}>
          <div className={styles.logoContainer}>
            <Image
              src={logo}
              width={200}
              height={200}
              alt="logo"
              className={styles.img}
            />
          </div>
          <h1>ELEGANT CONTEXT</h1>
          <div className={styles.shoppingCard}>
            <ShoppingCard onClick={handleOpenDialogClick} />
          </div>
        </nav>

        <div className={styles.sectionContainer}>
          <h3>ELEGANT CLOTHING FOR EVERYONE</h3>
          {isDialog && (
            <div className={styles.modal}>
              <CardModal onClick={handleCloseDialogClick} />;
            </div>
          )}
          <ul className={styles.ulContainer}>
            {DUMMY_PRODUCTS.map((element) => {
              return (
                <li key={element.id}>
                  <Card
                    id={element.id}
                    title={element.title}
                    description={element.description}
                    price={element.price}
                    img={element.image}
                  />
                </li>
              );
            })}
          </ul>
        </div>
      </main>
    </>
  );
}
